name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows running tests manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
